// Web/src/components/Layout/Layout.tsx
import { isH5 } from '../../utils';
import LayoutPC from './PC/Layout';
import LayoutH5 from './H5/Layout';

interface IPageLayout {
  children: JSX.Element;
}
export default function Layout(props: IPageLayout) {  
  return (
    <>
      {
        isH5 
          ? <LayoutH5> 
              <> {props.children} </> 
            </LayoutH5> 
          : <LayoutPC> 
              <> {props.children} </> 
            </LayoutPC>
      }
    </>
  )
}

// Web/basic-vue3/src/components/Layout/Layout.vue
<template>
  <LayoutPC v-if="!isH5">
    <slot />
  </LayoutPC>
  <LayoutH5 v-else>
    <slot />
  </LayoutH5>
</template>

<script lang="ts" setup>
import { isH5 } from '../../utils';
import LayoutPC from './PC/Layout.vue';
import LayoutH5 from './H5/Layout.vue';

</script>

<style lang="scss" scoped>
</style>
