// Web/demos/basic-vue3/src/pages/GroupCall/GroupCall.vue
<template>
  <GroupCallPC v-if="!isH5" />
  <GroupCallH5 v-else />
</template>

<script lang="ts" setup>
import { toRefs, onMounted } from 'vue';
import { useUserInfo, useMyRouter } from '../../hooks';
import { isH5 } from '../../utils';
import GroupCallPC from './PC/GroupCall.vue';
import GroupCallH5 from './H5/GroupCall.vue';


const { navigate } = useMyRouter();
const userInfo = toRefs(useUserInfo());

onMounted(() => {
  if (!userInfo?.isLogin.value) {
    navigate('/login');
  }
  userInfo.currentPage.value = 'call';
})

</script>

// Web/basic-react/src/pages/GroupCall/GroupCall.tsx
import { useEffect, useContext } from 'react';
import { useNavigate } from 'react-router-dom';
import { UserInfoContext } from '../../context';
import { isH5 } from "../../utils";
import GroupCallH5 from './H5/GroupCall';
import GroupCallPC from './PC/GroupCall';

export default function GroupCall() {
  const { userInfo, setUserInfo } = useContext(UserInfoContext);
  const navigate = useNavigate();
  
  useEffect(() => {
    if (!userInfo?.isLogin) {
      navigate('/login')
    }
    setUserInfo({
      ...userInfo,
      currentPage: 'groupCall',
    })
  }, []);

  return (
    <>
      {
        isH5 
          ? <GroupCallH5 />
          : <GroupCallPC />
      }
    </>
  )
}
