// Web/demos/basic-react/src/components/RunGuide/RunGuidePanel/RunGuidePanel.tsx

import { Tree, Flex, Image, Divider } from "antd"
import type { TreeDataNode } from 'antd';
import { useLanguage } from "../../../hooks";
import ChaSrc from '../../../assets/pages/cha.svg';
import GreenRightSrc from '../../../assets/runGuide/green-right.svg';
import './RunGuidePanel.css';


export interface IOperateDevicePanel {
  isShowPanel?: boolean,
  setIsShowPanel: React.Dispatch<boolean>;
}

interface IRunGuidePanelProps {
  operateRunGuidePanel: IOperateDevicePanel;
}

export default function RunGuidePanel(props: IRunGuidePanelProps) {

  const { setIsShowPanel } = props.operateRunGuidePanel;
  const { t } = useLanguage();

  const treeData: TreeDataNode[] = [
    { 
      title: `${t('Create / Log in userID')}`,
      key: 'step1',
    },
    {
      title: `${t('Complete Device Detection')}`,
      key: 'step2',
    },
    {
      title: `${t('Choose Video Call/Voice Call')}`,
      key: 'step3',
    },
    { 
      title: `${t('Initiate One-on-One Call')}`, 
      key: 'step4',
      children: [
        {
          title: `${t('Copy the link of this page to create a new user, or use your phone to scan the QR code')}`,
          key: 'step4-1',
        },
        {
          title: `${t('input the userID and initiate a one-on-one call')}`,
          key: 'step4-2',
        },
      ]
    },
    { 
      title: `${t('Initiate Group Call')}`, 
      key: 'step5',
      children: [
        {
          title: `${t('Copy the link of this page to create multiple users')}`,
          key: 'step5-1',
        },
        {
          title: `${t('Enter the userID and add up to 9 group members')}`,
          key: 'step5-2',
        },
        {
          title: `${t('Initiate Group Call')}`, 
          key: 'step5-3',
        },
      ]
    },
  ]

  const closePanel = () => {
    setIsShowPanel(false);
  }

  return (
    <>
      <Flex className="run-guide-panel" vertical={true}>
        <Flex justify="space-between">
          <span className="header-subCard-title"> {t('Run Demo Guide')} </span>
          <Image style={{cursor: 'pointer'}} src={ChaSrc} width={10} preview={false} onClick={closePanel} />
        </Flex>
        <Divider style={{margin: '16px 0'}} />
        <Tree
          showIcon
          showLine
          switcherIcon={<Image src={GreenRightSrc} preview={false} />}
          defaultExpandAll
          treeData={treeData}
        />
      </Flex>
    </>
  )
}

// Web/src/components/RunGuide/RunGuidePanel/RunGuidePanel.vue
<template>
  <div class="run-guide-box">
    <div class="header">
      <p> {{ t('Run Demo Guide') }} </p>
      <Icon :src="ChaSrc" :size="16" @click="$emit('closePanel')"  style="cursor: pointer;"/>
    </div>
    <p></p>
    <div>
      <el-tree
        :data="treeData"
        node-key="id"
        :default-expanded-keys="[4, 7]"
      />
    </div>
    
  </div>
</template>

<script lang='ts' setup>
import { useLanguage } from '../../../hooks';
import Icon from '../../common/Icon/Icon.vue';
import ChaSrc from '../../../assets/GroupCall/cha.svg';
// import GreenRightSrc from '../../../../assets/RunGuide/green-right.svg';
const { t } = useLanguage();

const treeData = [
  { 
    id: 1,
    label: t('Create / Log in userID'),
  },
  {
    id: 2,
    label: `${t('Complete Device Detection')}`,
  },
  {
    id: 3,
    label: `${t('Choose Video Call/Voice Call')}`,
  },
  { 
    id: 4,
    label: `${t('Initiate One-on-One Call')}`, 
    children: [
      {
        id: 5,
        label: `${t('Copy the link of this page to create a new user, or use your phone to scan the QR code')}`,
      },
      {
        id: 6,
        label: `${t('input the userID and initiate a one-on-one call')}`,
      },
    ]
  },
  { 
    id: 7,
    label: `${t('Initiate Group Call')}`, 
    children: [
      {
        id: 8,
        label: `${t('Copy the link of this page to create multiple users')}`,
      },
      {
        id: 9,
        label: `${t('Enter the userID and add up to 9 group members')}`,
      },
      {
        id: 10,
        label: `${t('Initiate Group Call')}`, 
      },
    ]
  },
];


</script>

<style lang="scss" scoped>
.run-guide-box {
  box-sizing: border-box;
  width: 308px;
  padding: 20px;
  background: #FFFFFF;
  box-shadow: 0px 3px 8px #E9F0FB;
  border-radius: 12px;
  position: absolute;
  z-index: 100;
  top: 80px;
  right: 20px;
  display: flex;
  flex-direction: column;
  gap: 16px 0;
  .header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    p {
      font-weight: 600;
      font-size: 16px;
    }
  }

  &>p {
    width: 268px;
    height: 0px;
    border: 1px solid rgba(228, 232, 238, 0.6);
  }
}
</style>
