// Web/basic-react/src/components/DeviceCheck/DeviceCheck.tsx
import { useState, useMemo } from 'react';
import { Button, Image, Typography } from "antd";
import useLanguage from '../../hooks/useLanguage.ts';
import DeviceCheckPanel from './DeviceCheckPanel/DeviceCheckPanel.tsx';
import DeviceCheckIcon from '../../assets/deviceCheck/device-check.svg';

const { Text } = Typography;

export default function DeviceCheck() {
  const { t } = useLanguage();
  const [isShowPanel, setIsShowPanel] = useState(false);
  const openDeviceCheckPanel = () => {
    setIsShowPanel(!isShowPanel);
  }
  const operateDevicePanel = useMemo(() => {
    return {
      isShowPanel,
      setIsShowPanel,
    }
  }, []);

  return (
    <>
      <Button onClick={openDeviceCheckPanel}>
        <Image src={DeviceCheckIcon} preview={false} />
        <Text> {t('Device Detection')} </Text>
      </Button>
      {
        isShowPanel && <DeviceCheckPanel operateDevicePanel={operateDevicePanel} />
      }
    </>
  )
}

// Web/web-callkit-demo/basic-vue3/src/components/DeviceCheck/DeviceCheck.vue
<template>
  <Card @click="handleIsShowPanel">
    <icon :src="DeviceCheckSrc" />
    {{  t('Device Detection') }}
  </Card>
  <DeviceCheckPanelVue @closePanel="handleIsShowPanel" v-if="isShowPanel" />
</template>

<script lang="ts" setup>
import { useLanguage } from '../../hooks';
import DeviceCheckSrc from '../../assets/DeviceCheck/device-check.svg';
import Card from '../common/Card/Card.vue';
import Icon from '../common/Icon/Icon.vue';
import DeviceCheckPanelVue from './DeviceCheckPanel/DeviceCheckPanel.vue';
import { ref } from 'vue';

const { t } = useLanguage();
const isShowPanel = ref(false);

const handleIsShowPanel = () => {
  isShowPanel.value = !isShowPanel.value;
}
</script>

<style lang="scss">

</style>
