// Web/basic-react/src/components/LanguageSwitch/LanguageSwitch.tsx
import { useMemo } from 'react';
import { Button, Dropdown, Image, Typography } from 'antd';
import { TUICallKitAPI } from '@trtc/calls-uikit-react';
import type { MenuProps } from 'antd';
import { LanguageType } from '../../interface/index';
import LanguageSwitchSrc from '../../assets/languageSwitch/language-switch.png';
import { useLanguage } from '../../hooks';
import { ClassNames, isH5 } from '../../utils';
import './LanguageSwitch.css';

const { Text } = Typography;

export default function LanguageSwitch() {
  const { changeLanguage, language } = useLanguage();
  const items = [
    { key: 'en', label: "English" },
    { key: 'zh-CN', label: "简体中文" },
    { key: 'ja', label: "日本語" },
  ];
  const lang = useMemo(() => {
    let res = 'English';
    items.map((item) => {
      if (item.key === language) res = item.label;
    })
    return res;
  }, [language]);

  const onClick: MenuProps['onClick'] = ({ key }) => {
    changeLanguage(key);
    // @ts-ignore
    TUICallKitAPI.setLanguage(LanguageType[key]);
  };
  
  return (
    <Dropdown
      menu={{ items, onClick, selectable: true, defaultSelectedKeys: [language] }} 
      placement="bottom"
    >
      <Button
        onClick={(e) => e.preventDefault()}
        className={ClassNames({'language-switch-card': isH5, 'header-card-pc': !isH5})}
      >
        <Image src={LanguageSwitchSrc} width={16} preview={false} /> 
        <Text className='header-card-text'> {lang} </Text>
      </Button>
    </Dropdown>
  )
}

// Web/basic-vue3/src/components/LanguageSwitch/LanguageSwitch.vue
<template>
  <el-dropdown
    placement="top-start"
    @command="handleCommand"
  >
    <Card>
      <Icon :src="LanguageSwitchSrc" :width="16"/>
      {{ showLang }}
    </Card>
    <template #dropdown>
      <el-dropdown-menu>
        <el-dropdown-item command="en"> English </el-dropdown-item>
        <el-dropdown-item command="zh_CN"> 简体中文 </el-dropdown-item>
        <el-dropdown-item command="ja"> 日本語 </el-dropdown-item>
      </el-dropdown-menu>
    </template>
  </el-dropdown>
</template>

<script lang="ts" setup>
import { computed, onMounted } from 'vue';
import { TUICallKitAPI } from '@trtc/calls-uikit-vue';
import Card from '../common/Card/Card.vue';
import Icon from '../common/Icon/Icon.vue';
import LanguageSwitchSrc from '../../assets/LanguageSwitch/language-swtich.svg';
import { useLanguage } from '../../hooks';

const { language, changeLanguage } = useLanguage();

const LanguageType = {
  'en': 'English',
  'zh_CN': '简体中文',
  'ja': '日本語',
} as { [key: string]: string };

const showLang = computed(() => LanguageType[language.value])

const LanguageTypeObj = {
  'en': 'en',
  'zh_CN': 'zh-cn',
  'ja': 'ja_JP',
} as { [key: string]: string };

const handleCommand = (command: string) => {
  changeLanguage(command);
  TUICallKitAPI.setLanguage(LanguageTypeObj[language.value]);
}

onMounted(() => {
  TUICallKitAPI.setLanguage(LanguageTypeObj[language.value]);
})

</script>
