// Web/basic-react/src/components/Instruction/Instruction.tsx
import { ConfigProvider, Typography, Image, Tooltip, Flex } from 'antd';
import { useLanguage } from '../../hooks';
import WarningSrc from '../../assets/instruction/warning.svg';
import HelpSrc from '../../assets/instruction/help.svg';
import RightArrowSrc from '../../assets/instruction/right-arrow.svg';
import './Instruction.css';

const { Text, Link } = Typography;

export default function Instruction() {
  const { t, language } = useLanguage();
  return (
    <ConfigProvider
      theme={{
        components: {
          Typography: {
            colorLink: '#1C66E5',
            colorLinkActive: '#1C66E5',
            colorLinkHover: '#1C66E5'
          },
        },
      }}
    >
      <div className='instruction-card'>
        <Image 
          src={WarningSrc} 
          width={16} 
          preview={false} 
        />
        <Text className='instruction-text'>
          {t('Sensitive links/QR')}
        </Text>
      </div>
      <div className='instruction-card' style={{marginLeft: '10px'}}>
        <Image 
          src={HelpSrc} 
          width={16} 
          preview={false} 
        />
        <Flex align='center'>
          <Text  className='instruction-text'> 
            {t('Any problems in running')}
          </Text>
          {
            language.includes('zh') 
              ? (
                  <Tooltip title="腾讯云官方社群: https://zhiliao.qq.com/">
                    <Link 
                      className='instruction-link'
                      href="https://zhiliao.qq.com/" 
                      target='_blank'
                    >
                      {t('Get tech support')}
                      <Image src={RightArrowSrc} width={16} preview={false} />
                    </Link>
                  </Tooltip>
                ) 
              : (
                  <Tooltip title="Telegram: https://t.me/+EPk6TMZEZMM5OGY1">
                    <Link
                      className='instruction-link'
                      href="https://t.me/+EPk6TMZEZMM5OGY1"
                      target='_blank'
                    >
                      {t('Get tech support')}
                      <Image src={RightArrowSrc} width={16} preview={false} />
                    </Link>
                  </Tooltip>
                )
          }
        </Flex>
      </div>
    </ConfigProvider>
  )
}

// Web/basic-vue3/src/components/Layout/Instruction/Instruction.vue
<template>
  <Space size="12px">
    <Card> 
      <Icon :src="WarningSrc" />
      {{ t('Sensitive links/QR') }}
    </Card>
    <Card>
      <Icon :src="HelpSrc" />
      {{ t('Any problems in running') }}
      <el-link
        :href="link"
        target="_blank"
        style="margin-left: 77px; color: #1C66E5;"
        :underline="false"
      >
        {{ t('Get tech support') }}
        <Icon :src="RightArrowSrc" :size="16"/>
      </el-link>
    </Card>
  </Space>
</template>

<script lang="ts" setup>
import { useLanguage } from '../../../hooks';
import Icon from '../../common/Icon/Icon.vue';
import Card from '../../common/Card/Card.vue';
import Space from '../../common/Space/Space.vue';
import WarningSrc from '../../../assets/Layout/warning.svg';
import HelpSrc from '../../../assets/Layout/help.svg';
import RightArrowSrc from '../../../assets/Layout/right-arrow.svg';
import { computed } from 'vue';

const { t, language } = useLanguage();
const link = computed(() => {
  return language.value.includes('zh')
    ? 'https://zhiliao.qq.com/'
    : 'https://t.me/+EPk6TMZEZMM5OGY1'
})

</script>
