// Web/basic-vue3/src/pages/Login/Login.vue
<template>
  <LoginPC v-if="!isH5"/>
  <LoginH5 v-else/>
</template>

<script setup lang="ts">
import { onMounted, toRefs } from 'vue';
import { isH5, getUrlParams } from '../../utils';
import { useUserInfo } from '../../hooks';
import LoginPC from './PC/Login.vue';
import LoginH5 from './H5/Login.vue';

const userInfo = toRefs(useUserInfo());

onMounted(() => {
  const { SDKAppID, SecretKey } = getUrlParams(['SDKAppID', 'SecretKey']);
  userInfo.SDKAppID.value = Number(SDKAppID);
  userInfo.SecretKey.value = SecretKey;
  userInfo.currentPage.value = 'login';
})

</script>

// Web/basic-react/src/pages/Login/Login.tsx
import { useEffect, useContext } from 'react';
import { UserInfoContext } from '../../context';
import { isH5, getUrlParams } from '../../utils';
import LoginPC from './PC/Login';
import LoginH5 from './H5/LoginH5';

export default function Login() {
  const { userInfo, setUserInfo } = useContext(UserInfoContext);
  useEffect(() => {
    const { SDKAppID, SecretKey } = getUrlParams(['SDKAppID', 'SecretKey']);
    setUserInfo({
      ...userInfo,
      SDKAppID: Number(SDKAppID),
      SecretKey,
      currentPage: 'login',
      userID: '',
      isLogin: false,
    });
  }, []);

  return (
    <>
      {
        isH5 ? <LoginH5 /> : <LoginPC />
      }
    </>
  )
}
