// Web/src/components/Layout/PC/Layout.vue
<template>
  <el-container>
    <el-header height="70px" class="layout-header">
      <Space size="12px">
        <LanguageSwitch />
        <DeviceCheck />
        <RunGuide />
      </Space>
    </el-header>
    <el-main class="layout-main">
      <Logo/>
      <Container>
        <slot />
      </Container>
      <QuickLink />
    </el-main>
    <el-footer height="70px" class="layout-footer">
      <Instruction />
    </el-footer>
  </el-container>
</template>

<script lang="ts" setup>
import LanguageSwitch from '../../LanguageSwitch/LanguageSwitch.vue';
import DeviceCheck from '../../DeviceCheck/DeviceCheck.vue';
import RunGuide from '../../RunGuide/RunGuide.vue';
import Instruction from '../Instruction/Instruction.vue';
import QuickLink from '../../QuickLink/QuickLink.vue';
import Logo from '../Logo/Logo.vue';
import Container from '../Container/Container.vue';
import Space from '../../common/Space/Space.vue';

</script>

<style lang="scss" scoped>
.layout-header {
  display: flex;
  justify-content: end;
  align-items: end;
}
.layout-main {
  height: calc(100vh - 140px);
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
}
.layout-footer {
  display: flex;
  justify-content: center;
  align-items: start;
}
</style>

// Web/basic-react/src/components/Layout/Layout.tsx
import { Flex, Layout, Image, Space } from 'antd';
import { useLanguage } from '../../hooks';
import { IContentProps } from '../../interface/index';
import QuickLink from './QuickLink/QuickLink';
import DeviceCheck from '../DeviceCheck/DeviceCheck';
import LanguageSwitch from '../LanguageSwitch/LanguageSwitch';
import Instruction from '../Instruction/Instruction';
import logoEnSrc from '../../assets/layout/logo-en.png';
import logoZhSrc from '../../assets/layout/logo-zh.png';
import './Layout.css';

export default function PageLayout(props: IContentProps) {  
  const { Header, Footer, Content } = Layout;
  const { children } = props;
  const { language } = useLanguage();

  return (
    <Layout>
      <Header>
        <Flex justify="flex-end" align='center'>
          <Space>
            <LanguageSwitch />
            <DeviceCheck />
            {/* <RunGuide /> */}
          </Space>
        </Flex>
      </Header>
      <Content className='layout-middle'>
        <Flex vertical={true} justify='center' align='center'>
           <Layout>
            <Header>
              <Flex justify='center'>
                {
                  language === 'zh' 
                    ? <Image src={logoZhSrc} width={213} preview={false} /> 
                    : <Image src={logoEnSrc} width={213} preview={false} />
                }
              </Flex>
            </Header>
            <Content className='layout-card'>
              {children}
            </Content>
            <Footer>
              <Flex justify='center'>
                <Space>
                  <QuickLink />
                </Space>
              </Flex>
            </Footer>
          </Layout>
        </Flex>
      </Content>
      <Footer className='layout-footer'>
        <Instruction />
      </Footer>
    </Layout>
  )
}
