// Web/web-callkit-demo/basic-vue3/src/pages/Home/Home.vue
<template>
  <HomePC v-if="!isH5" />
  <HomeH5 v-else/>
</template>
<script lang="ts" setup>
import { onMounted, toRefs } from 'vue';
import { useMyRouter, useUserInfo } from '../../hooks';
import { isH5 } from '../../utils';
import HomePC from './PC/Home.vue';
import HomeH5 from './H5/Home.vue';

const { navigate } = useMyRouter();
const userInfo = toRefs(useUserInfo());

onMounted(() => {
  if (!userInfo?.isLogin.value) {
    navigate('/login');
  }
  userInfo.currentPage.value = 'home';
})

</script>

// Web/basic-react/src/pages/Home/Home.tsx
import { useEffect, useContext } from 'react';
import { useNavigate } from 'react-router-dom';
import { UserInfoContext } from '../../context';
import { isH5 } from '../../utils';
import HomePC from './PC/Home';
import HomeH5 from './H5/Home';

export default function Home() {
  const navigate = useNavigate()
  const { userInfo, setUserInfo } = useContext(UserInfoContext);

  useEffect(() => {
    if (!userInfo.isLogin) {
      navigate('/login');
    }
    setUserInfo({
      ...userInfo,
      currentPage: 'home',
    })
  }, []);
  
  return (
    <>
      {
        isH5 ? <HomeH5 /> : <HomePC />
      }
    </>
  )
}
